default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: adela_development
  username: adela
  password: adela
  host: 172.17.0.3

test:
  <<: *default
  database: adela_test
  username: adela
  password: adela
  host: 172.0.0.1

production:
  <<: *default
  database: adela_production
  username: postgres
  host: localhost
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
